version: '3.7'
services:
  webapp:
    image: spanishhans/cet-mineria:webapp
    container_name: web_app
    restart: unless-stopped
    ports:
      - '10305:5000'
    networks:
      - backend

networks:
  backend:
    name: back_web
    driver: bridge
